//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace NSBT_WS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/action/", ConfigurationName="NSBT_WS.X9996C1SoapPort")]
    public interface X9996C1SoapPort
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/action/action/AX9996C1.Execute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NSBT_WS.ExecuteResponse> ExecuteAsync(NSBT_WS.ExecuteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="X9996C1.Execute", WrapperNamespace="http://tempuri.org/action/", IsWrapped=true)]
    public partial class ExecuteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=0)]
        public short Acnco { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Dfecl { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=2)]
        public string Dhocl { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=3)]
        public string Drqcl { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=4)]
        public short Bopco { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=5)]
        public short Cvart { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=6)]
        public string Drqus { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=7)]
        public string Drqws { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=8)]
        public short Ddpgc { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=9)]
        public short Ddsuc { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=10)]
        public short Ddmod { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=11)]
        public short Ddmda { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=12)]
        public short Ddpap { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=13)]
        public int Ddcta { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=14)]
        public int Ddope { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=15)]
        public short Ddsbo { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=16)]
        public short Ddtop { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=17)]
        public short Dcpgc { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=18)]
        public short Dcsuc { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=19)]
        public short Dcmod { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=20)]
        public short Dcmda { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=21)]
        public short Dcpap { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=22)]
        public int Dccta { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=23)]
        public int Dcope { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=24)]
        public short Dcsbo { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=25)]
        public short Dctop { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=26)]
        public double Dimpo { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=27)]
        public double Dimp2 { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=28)]
        public short Dmdao { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=29)]
        public double Dcotz { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=30)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public string[] Edatos { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=31)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public string[] Etdats { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=32)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public string[] Evalcs { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=33)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public string[] Evalls { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=34)]
        public short Ecantlin { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=35)]
        public string Hashreq { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=36)]
        public short Drpgc { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=37)]
        public short Drsuc { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=38)]
        public short Drmod { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=39)]
        public short Drtrn { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=40)]
        public short Drrel { get; set; }

        public ExecuteRequest()
        {
            // Fecha
            this.Dfecl = System.DateTime.Now;
            // Hora
            this.Dhocl = System.DateTime.Now.ToString("HHmmssff");
            // Identificador único
            this.Drqcl = "Api-usuarios: " + Guid.NewGuid().ToString();

            // Cuenta Débito
            this.Ddpgc = 0;
            this.Ddsuc = 0;
            this.Ddmod = 0;
            this.Ddmda = 0;
            this.Ddpap = 0;
            this.Ddcta = 0;
            this.Ddope = 0;
            this.Ddsbo = 0;
            this.Ddtop = 0;

            // Cuenta Crédito
            this.Dcpgc = 0;
            this.Dcsuc = 0;
            this.Dcmod = 0;
            this.Dcmda = 0;
            this.Dcpap = 0;
            this.Dccta = 0;
            this.Dcope = 0;
            this.Dcsbo = 0;
            this.Dctop = 0;

            // Importe
            this.Dimpo = 0.0;
            this.Dimp2 = 0.0;
            this.Dmdao = 0;
            this.Dcotz = 0.0;

            this.Edatos = new string[20];
            this.Etdats = new string[20];
            this.Evalcs = new string[20];
            this.Evalls = new string[20];

            //// Parámetros
            for (int i = 0; i < 20; i++)
            {
                this.Edatos[i] = "";
                this.Etdats[i] = "";
                this.Evalcs[i] = "";
                this.Evalls[i] = "";
            }

            // Luego de Parámetros
            this.Ecantlin = 0;
            this.Hashreq = "";
            this.Drpgc = 0;
            this.Drsuc = 0;
            this.Drmod = 0;
            this.Drtrn = 0;
            this.Drrel = 0;
        }
        
        public ExecuteRequest(
                    short Acnco, 
                    System.DateTime Dfecl, 
                    string Dhocl, 
                    string Drqcl, 
                    short Bopco, 
                    short Cvart, 
                    string Drqus, 
                    string Drqws, 
                    short Ddpgc, 
                    short Ddsuc, 
                    short Ddmod, 
                    short Ddmda, 
                    short Ddpap, 
                    int Ddcta, 
                    int Ddope, 
                    short Ddsbo, 
                    short Ddtop, 
                    short Dcpgc, 
                    short Dcsuc, 
                    short Dcmod, 
                    short Dcmda, 
                    short Dcpap, 
                    int Dccta, 
                    int Dcope, 
                    short Dcsbo, 
                    short Dctop, 
                    double Dimpo, 
                    double Dimp2, 
                    short Dmdao, 
                    double Dcotz, 
                    string[] Edatos, 
                    string[] Etdats, 
                    string[] Evalcs, 
                    string[] Evalls, 
                    short Ecantlin, 
                    string Hashreq, 
                    short Drpgc, 
                    short Drsuc, 
                    short Drmod, 
                    short Drtrn, 
                    short Drrel)
        {
            this.Acnco = Acnco;
            this.Dfecl = Dfecl;
            this.Dhocl = Dhocl;
            this.Drqcl = Drqcl;
            this.Bopco = Bopco;
            this.Cvart = Cvart;
            this.Drqus = Drqus;
            this.Drqws = Drqws;
            this.Ddpgc = Ddpgc;
            this.Ddsuc = Ddsuc;
            this.Ddmod = Ddmod;
            this.Ddmda = Ddmda;
            this.Ddpap = Ddpap;
            this.Ddcta = Ddcta;
            this.Ddope = Ddope;
            this.Ddsbo = Ddsbo;
            this.Ddtop = Ddtop;
            this.Dcpgc = Dcpgc;
            this.Dcsuc = Dcsuc;
            this.Dcmod = Dcmod;
            this.Dcmda = Dcmda;
            this.Dcpap = Dcpap;
            this.Dccta = Dccta;
            this.Dcope = Dcope;
            this.Dcsbo = Dcsbo;
            this.Dctop = Dctop;
            this.Dimpo = Dimpo;
            this.Dimp2 = Dimp2;
            this.Dmdao = Dmdao;
            this.Dcotz = Dcotz;
            this.Edatos = Edatos;
            this.Etdats = Etdats;
            this.Evalcs = Evalcs;
            this.Evalls = Evalls;
            this.Ecantlin = Ecantlin;
            this.Hashreq = Hashreq;
            this.Drpgc = Drpgc;
            this.Drsuc = Drsuc;
            this.Drmod = Drmod;
            this.Drtrn = Drtrn;
            this.Drrel = Drrel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="X9996C1.ExecuteResponse", WrapperNamespace="http://tempuri.org/action/", IsWrapped=true)]
    public partial class ExecuteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public string[] Edatos { get; set; }
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public string[] Etdats { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public string[] Evalcs { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public string[] Evalls { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=4)]
        public short Ecantlin { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Dfesv { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=6)]
        public string Dhosv { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=7)]
        public int Drqsv { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=8)]
        public string Grsco { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=9)]
        public short Drpgc { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=10)]
        public short Drsuc { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=11)]
        public short Drmod { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=12)]
        public short Drtrn { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=13)]
        public short Drrel { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=14)]
        public short Drmnc { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=15)]
        public double Drsdo { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=16)]
        public double Drsdd { get; set; }

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/action/", Order=17)]
        public string Xml { get; set; }

        public static string OkResponse = "OK";

        public ExecuteResponse()
        {
        }
        
        public ExecuteResponse(
                    string[] Edatos, 
                    string[] Etdats, 
                    string[] Evalcs, 
                    string[] Evalls, 
                    short Ecantlin, 
                    System.DateTime Dfesv, 
                    string Dhosv, 
                    int Drqsv, 
                    string Grsco, 
                    short Drpgc, 
                    short Drsuc, 
                    short Drmod, 
                    short Drtrn, 
                    short Drrel, 
                    short Drmnc, 
                    double Drsdo, 
                    double Drsdd, 
                    string Xml)
        {
            this.Edatos = Edatos;
            this.Etdats = Etdats;
            this.Evalcs = Evalcs;
            this.Evalls = Evalls;
            this.Ecantlin = Ecantlin;
            this.Dfesv = Dfesv;
            this.Dhosv = Dhosv;
            this.Drqsv = Drqsv;
            this.Grsco = Grsco;
            this.Drpgc = Drpgc;
            this.Drsuc = Drsuc;
            this.Drmod = Drmod;
            this.Drtrn = Drtrn;
            this.Drrel = Drrel;
            this.Drmnc = Drmnc;
            this.Drsdo = Drsdo;
            this.Drsdd = Drsdd;
            this.Xml = Xml;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface X9996C1SoapPortChannel : NSBT_WS.X9996C1SoapPort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class X9996C1SoapPortClient : System.ServiceModel.ClientBase<NSBT_WS.X9996C1SoapPort>, NSBT_WS.X9996C1SoapPort
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public X9996C1SoapPortClient() : 
                base(X9996C1SoapPortClient.GetDefaultBinding(), X9996C1SoapPortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.X9996C1SoapPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public X9996C1SoapPortClient(string remoteAddress) :
                base(X9996C1SoapPortClient.GetDefaultBinding(), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = EndpointConfiguration.X9996C1SoapPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public X9996C1SoapPortClient(EndpointConfiguration endpointConfiguration) : 
                base(X9996C1SoapPortClient.GetBindingForEndpoint(endpointConfiguration), X9996C1SoapPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public X9996C1SoapPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(X9996C1SoapPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public X9996C1SoapPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(X9996C1SoapPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public X9996C1SoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<NSBT_WS.ExecuteResponse> ExecuteAsync(NSBT_WS.ExecuteRequest request)
        {
            return base.Channel.ExecuteAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.X9996C1SoapPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.X9996C1SoapPort))
            {
                return new System.ServiceModel.EndpointAddress("http://nsbtinter/bantotal/servlet/com.dlya.bantotal.ax9996c1");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return X9996C1SoapPortClient.GetBindingForEndpoint(EndpointConfiguration.X9996C1SoapPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return X9996C1SoapPortClient.GetEndpointAddress(EndpointConfiguration.X9996C1SoapPort);
        }
        
        public enum EndpointConfiguration
        {
            
            X9996C1SoapPort,
        }
    }
}
