variables:
  APP_NAME: bff-usuarios
  REPO_NAME: usuarios
  BUILD_GROUP: snapshot
  RESOURCE_PATH: .
  GROUP_ID: ar/com/supervielle
  REPO_GENERIC: ${REPO_NAME}-generic-local
  REPO_DOCKER: $REPO_NAME.artifactory.gscorp.ad
  REPO_SPV: docker-spv.artifactory.gscorp.ad
  DOCKERFILE: .
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ''
  SONAR_HOST_URL: "https://sonarqubede.gscorp.ad"
  GIT_DEPTH: 0

before_script: 
    - export BUILD_VERSION=$(cat VERSION)

stages:
  - CodeQuality
  - Build
  - Package
  - Deploy
  - Release

include:
  - project: 'gitlab-ci-templates/kubernetes'
    ref: 'master'
    file: '.build.yml'
  - project: 'gitlab-ci-templates/kubernetes'
    ref: 'master'
    file: '.package.yml'
  - project: 'gitlab-ci-templates/kubernetes'
    ref: 'master'
    file: '.deploy.yml'
  - project: 'gitlab-ci-templates/kubernetes'
    ref: 'master'
    file: '.codequalityv2.yml'
  - project: 'gitlab-ci-templates/kubernetes'
    ref: 'master'
    file: '.release.yml'
