--- 
apiVersion: v1
data: 
  appsettings.json: |
      {
         "AllowedHosts": "*",
         "BffUsuarios": {
           "Authority": "{{ (ds "properties").CONFIG.Authority }}",
           "Audience": "{{ (ds "properties").CONFIG.Audience }}"
         },
         "OpenApiInfo": {
           "Title": "BFF OBI Usuarios",
           "Contact": "CredencialesDigitales@supervielle.com.ar",
           "TermsOfService": "http://supervielle.com.ar"
         },
         "ApiServices": { 
            "xCanal": "{{ (ds "properties").CONFIG.xCanal }}", 
            "xUsuario": "{{ (ds "properties").CONFIG.xUsuario }}",
            "xAplicacion": "{{ (ds "properties").CONFIG.xAplicacion }}",
            "xGateway": "{{ (ds "properties").CONFIG.xGateway }}"  
          },
         "IbmApiConnect": {
            "Host": "{{ (ds "properties").CONFIG.IbmApiConnect_Host }}",
            "ClientId": "{{ (ds "properties").SECRET.IbmApiConnect_ClientId }}"
          },
         "ApiPersonas": {
           "BasePath": "{{ (ds "properties").CONFIG.ApiPersonas_BasePath }}",
           "PersonasPath": "/v2.0/personas?numero_documento={0}&tipo_documento={1}&pais_documento={2}",
           "PersonasFiltroPath": "/v2.0/personas/filtro?numero_documento={0}",
           "PersonasInfoPath": "/v2.0/personas/{0}",
           "PersonasFisicaInfoPath": "/v2.0/fisicas/{0}",
           "TelefonosPath": "/v2.0/personas/{0}/telefonos",
           "TelefonosDobleFactorPath": "/v2.0/personas/{0}/telefonos/doble-factor",
           "TelefonosVerificacionPath": "/v2.0/telefonos/{0}/verificaciones",
           "EmailsPath": "/v2.0/personas/{0}/emails",
           "CacheExpiracionTyCMinutos": {{ (ds "properties").CONFIG.CacheExpiracionTyCMinutos }}
         },
         "ApiCatalogo": {
           "BasePath": "{{ (ds "properties").CONFIG.ApiCatalogo_BasePath }}",
           "PaisesPath": "/v1.0/paises",
           "TiposDocumentoPath": "/v1.0/tipos-documento"
         },
         "ApiUsuarios": {
           "BasePath": "{{ (ds "properties").CONFIG.ApiUsuarios_BasePath }}",
           "ValidarClaveCanalesPath": "/v2/clave-canales/validacion",
           "InhabilitarClaveCanalesPath": "/v2/clave-canales/inhabilitacion",
           "ObtenerEstadoClaveCanalesPath": "/v2/clave-canales/obtener-estado",
           "RegistrarUsuarioPath": "/v2/usuarios/registracion",
           "MigrarUsuarioPath": "/v2/usuarios/migracion",
           "PerfilPath": "/v1/usuarios/{0}/perfil",
           "PerfilPathV2": "/v2/usuarios/{0}/perfil",
           "ValidarExistenciaPath": "/v2/usuarios/validacion-existencia",
           "ValidarExistenciaHbiPath": "/v1/usuarios/validacion-existencia",
           "CambiarCredencialesPath": "/v2/usuarios/cambio-de-credenciales",
           "CambiarClavePath": "/v2/usuarios/cambio-de-clave",
           "ActualizarPersonIdPath": "/v2/usuarios/actualizar-personId",
           "AutenticacionPath": "/v2/sso/autenticacion",
           "ObtenerUsuarioPath": "/v2/usuarios/obtener-usuario?nro_documento={0}&usuario={1}",
           "ObtenerImagenesLoginPath": "/v2/dynamicImages/obtener-images-login",
           "CacheExpiracionTyCMinutos": {{ (ds "properties").CONFIG.CacheExpiracionTyCMinutos }},
           "CacheExpiracionImagenesLoginMinutos": {{ (ds "properties").CONFIG.CacheExpiracionImagenesLoginMinutos }}
         },
         "Configuraciones": {
           "TYCHabilitadoPath": "/v2/configuraciones/terminos-condiciones-habilitado",
           "LoginHabilitadoPath": "/v2/configuraciones/login-habilitado",
           "MensajeDefaultLoginDeshabilitadoPath": "/v2/configuraciones/mensaje-default-login-deshabilitado",
           "MensajeLoginDeshabilitadoPath": "/v2/configuraciones/mensaje-login-deshabilitado"
          },
         "ApiNotificaciones": {
            "BasePath": "{{ (ds "properties").CONFIG.ApiNotificaciones_BasePath }}",
            "CrearYEnviarTokenPath": "/v1.0/token",
            "ValidarTokenPath": "/v1.0/token/validacion",
            "EnviarEmailPath": "/v1.0/notificaciones",           
            "TiempoRespuestaEnvioMails":"{{ (ds "properties").CONFIG.TiempoRespuestaEnvioMails }}"
         },
         "ApiTyC": {
            "BasePath": "{{ (ds "properties").CONFIG.ApiTyC_BasePath }}",
            "TerminosYCondicionesVigentePath": "/v2/terminosycondiciones-vigente?canal={0}&concepto={1}",
            "TerminosYCondicionesAceptadosPath": "/v2/terminosycondiciones-aceptados",
            "ConceptoRegistracion": "{{ (ds "properties").CONFIG.TyC_ConceptoRegistracion }}",
            "CacheExpiracionTyCMinutos": {{ (ds "properties").CONFIG.CacheExpiracionTyCMinutos }}
         },
         "ApiSoftToken": {
            "BasePath": "{{ (ds "properties").CONFIG.ApiSoftToken_BasePath }}",
            "TokenHabilitado": "/v1.0/tokens/",
            "TokenValido": "/v1.0/tokens/{0}/validacion",
            "TokenIdentificador": "{{ (ds "properties").CONFIG.ApiSoftToken_Identificador }}",
         },
         "ApiScoreOperaciones": {
            "BasePath": "{{ (ds "properties").CONFIG.ApiScoreOperaciones_BasePath }}",
            "UpdateCredentials": "/v1.0/no-monetario/actualizar-credenciales",
            "RegistracionScore": "/v1.0/no-monetario/registracion",
            "IniciarSesionScore": "/v1.0/no-monetario/inicio-de-sesion"
         },
         "ApiGoogle": {
            "Host": "https://www.google.com",
            "ValidacionTokenCaptchaV3Path": "/recaptcha/api/siteverify",
            "SecretCaptchaV3Key": "{{ (ds "properties").SECRET.SecretCaptchaV3Key }}"
         },
         "ApiBiometria": {
             "BasePath": "{{ (ds "properties").CONFIG.ApiBiometria_BasePath }}",
             "Autenticacion": "/v1.0/autenticaciones"
         },
         "Seguridad": {
           "Origins.Cors": "{{ (ds "properties").CONFIG.CORS }}"
         },
         "Hangfire": {
           "User": "{{ (ds "properties").CONFIG.Hangfire.User }}",
           "Password": "gNbJPOmglk2t58qGj6aVgQ=="
         },
         "HealthChecksUI": {
           "HealthChecks": [
           {
             "Name": "Bff Usuarios",
             "Uri": "http://localhost/health-ui"
           }
           ],
           "EvaluationTimeOnSeconds": 10,
           "MinimumSecondsBetweenFailureNotifications": 60
         },
         "Serilog": {
           "Using": [ "Serilog.Settings.Configuration", "Serilog.Formatting.Compact" ],
           "MinimumLevel": {
             "Default": "{{ (ds "properties").CONFIG.DEFAULT_LOG_LEVEL }}",
             "Override": {
               "Microsoft.EntityFrameworkCore": "Warning",
               "AspNetCore.HealthChecks.UI": "Warning",
               "HealthChecks": "Warning",
               "Microsoft": "Warning",
               "System": "Warning"
             }
         },
         "Filter": [
            {
              "Name": "ByExcluding",
              "Args": {
                "expression": "RequestPath like '%/health%' or RequestPath like '%/info'"
              }
            }
         ],
         "WriteTo": [
           {
             "Name": "File",
             "Args": {
               "path": "/var/log/app.log",
               "formatter": "Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact",
               "retainedFileCountLimit": 3,
               "rollOnFileSizeLimit": true,
               "fileSizeLimitBytes": 500000000 //500mb
             }
           },
           {
             "Name": "File",
             "Args": {
               "path": "log.txt",
               "rollingInterval": "Day",
               "retainedFileCountLimit": 30,
               "rollOnFileSizeLimit": true,
               "fileSizeLimitBytes": 50000000, //50mb
               "buffered": false,
               "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss} [{Level:u3}] {CorrelationId} {Message:lj}{NewLine}{Exception}"
             }
           }
         ]
       }
      }
kind: ConfigMap
metadata:
   creationTimestamp: null
   name: {{ (ds "properties").APP_NAME }}-cm
   namespace: {{ (ds "properties").NAMESPACE }}
